name: Test

on:
  push: 
    branches:
      - '**'
      - '!main'
  
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lab: [lab_1, lab_2]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install googletest
        uses: cvpkg/googletest-action@v0.1
        with:
          googletest_tag: 'release-1.11.0'

      - name: run tests
        run: |
          cd ${{ matrix.lab }}/build
          ./tests 